### ISSUE TITLE
checking if proxy works is broken.

### ISSUE THREAD

**Issue by JohnNielse** [mikelucid/proxydrip#1]
It will always say Proxy isnt working and delete the droplet. Even if its working fine.

happends Mac os big sur and Kali Linux.
I have not tried windows

**Comment by mikelucid** [comment]
ill take a look. i might have messed something up  in the last commit

**Comment by ipwnosx** [comment]
bruh messed something up??
90% of the dependencies are deprecated & broken... this shit has got issues

**Comment by mikelucid** [comment]
everything seems to be working with nothing depreciated or broken....
